version: '3.8'

services:
  # Development service
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ecommerce-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./package.json:/app/package.json
      - frontend-dev-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production service
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ecommerce-frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - ecommerce-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M

volumes:
  frontend-dev-node_modules:

networks:
  ecommerce-network:
    driver: bridge

