version: '3.8'

services:
  # Development service
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ecommerce-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./tests:/app/tests
      - ./examples:/app/examples
      - backend-dev-db:/app/data
    working_dir: /app
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=sqlite:///./data/ecommerce.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key-change-in-production}
      - LOG_LEVEL=DEBUG
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production service
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ecommerce-backend-prod
    ports:
      - "8000:8000"
    volumes:
      - backend-prod-db:/app/data
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - DATABASE_URL=sqlite:///./data/ecommerce.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    env_file:
      - .env.production
    networks:
      - ecommerce-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M

volumes:
  backend-dev-db:
  backend-prod-db:

networks:
  ecommerce-network:
    driver: bridge

