name: "MassiveRefactoringAgent"
description: "Performs large-scale refactoring operations with comprehensive testing"
version: "1.0.0"

triggers:
  - manual_execution
  - scheduled: "0 2 * * SUN"  # Sunday 2 AM
  - git_event:
      branch: "main"
      files_changed: ">50"

capabilities:
  - code_analysis
  - pattern_detection
  - refactoring_execution
  - test_generation
  - documentation_update

parameters:
  scope:
    type: "string"
    options: ["component", "module", "entire_project"]
    default: "module"

  safety_level:
    type: "string"
    options: ["conservative", "moderate", "aggressive"]
    default: "moderate"

execution_steps:
  - name: "analyze_codebase"
    description: "Deep analysis of current patterns and inconsistencies"
    timeout: "30m"

  - name: "generate_refactoring_plan"
    description: "Create detailed refactoring strategy with impact analysis"
    timeout: "15m"

  - name: "execute_refactoring"
    description: "Apply refactoring changes incrementally"
    timeout: "2h"
    safety_checks: true

rollback_strategy:
  enabled: true
  automatic_triggers:
    - test_failure_rate: ">5%"
    - build_failure
    - performance_regression: ">20%"